### ISSUE TITLE
require.paths removed in node 0.6

### ISSUE THREAD

**Issue by sublimino** [zendeskarchive/jessie#12]
node.js:207
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
...

Using nave, commenting out the require.paths and adding ~/.npm/jessie/0.3.7/package/spec and ~/.npm/jessie/0.3.7/package/lib to $NODE_PATH allows Jessie to execute.

**Comment by GraemeF** [comment]
I think this was actually removed in node 0.5, but I'm new to all this. Anyway, I'm getting this error in node 0.5.9.

**Comment by sublimino** [comment]
This will be fixed by https://github.com/futuresimple/jessie/pull/14
