### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by ghost** [zendeskarchive/jessie#6]
Hello, newbie here ...

Step by step on a ubuntu 11.04:
1)mkdir project
2) cd project
3) mkdir specs
4) cd specs
5) create file test01.js containing :
describe('A test', function(){
  it('should fail', function(){
    expect(1).toEqual(2)
  })
})
6) cd ..
7) npm install jessie
8) jessie specs/
9) output: Completed in 0.001 seconds
0 example

**Comment by marcinbunsch** [comment]
Hi!

Jessie assumes the spec files end with _spec.js, so in your case the file should be named "test01_spec.js". Try renaming the file and running the "jessie specs" again.

**Comment by ghost** [comment]
Thanks
